### ISSUE TITLE
negative values not handled

### ISSUE THREAD

**Issue by wirlygig** [Regaddi/Chart.StackedBar.js#15]
the sample code does not take into account negatives. when a negative value is entered it shows off grid. Is it possible to get the bar chart to also handle a negative value?

Example:

  var randomScalingFactor = function () { return Math.round(Math.random() * 100) };
        var barChartData = {
            labels: ["January", "February", "March", "April", "May", "June", "July"],
            datasets: [
        {
            fillColor: "rgba(220,220,220,0.5)",
            strokeColor: "rgba(220,220,220,0.8)",
            highlightFill: "rgba(220,220,220,0.75)",
            highlightStroke: "rgba(220,220,220,1)",
            data: [-129, 52, 7, 42, 16, 0, 3]
        },
        {
            fillColor: "rgba(151,187,205,0.5)",
            strokeColor: "rgba(151,187,205,0.8)",
            highlightFill: "rgba(151,187,205,0.75)",
            highlightStroke: "rgba(151,187,205,1)",
            data: [randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor()]
        },
        {
            fillColor: "rgba(240,73,73,0.5)",
            strokeColor: "rgba(240,73,73,0.8)",
            highlightFill: "rgba(240,73,73,0.75)",
            highlightStroke: "rgba(240,73,73,1)",
            data: [randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor()]
        }
        ]
        };
        window.onload = function () {
            var ctx = document.getElementById("canvas").getContext("2d");
            window.myBar = new Chart(ctx).StackedBar(barChartData, {
                responsive: true
            });
        };

**Comment by Regaddi** [comment]
Hi @wirlygig,

Sorry for the late response!

If you need to handle negative values I suggest not to use this extension, since this particular way of visualizing data is not sufficient for your use case.
For negative values you'd rather use a non-stacked bar chart or line chart, which allows negative values for comparison.
