### ISSUE TITLE
Bars overlap each other sometimes

### ISSUE THREAD

**Issue by nozzle** [Regaddi/Chart.StackedBar.js#19]

**Comment by tannerlinsley** [comment]
You can see in this image that some of the blue and green are overlapping each other.  Since the green is getting drawn on top of the blue, the blue is almost none existent.  I've taken the opacity down on most of the bars to see the effect a bit better.

![](http://i.snag.gy/fPsbK.jpg)

**Comment by Regaddi** [comment]
Can you please post an example code?

**Comment by Regaddi** [comment]
Still need example code ;)
