### ISSUE TITLE
Cannot handle data when given an array of integers as strings.

### ISSUE THREAD

**Issue by Vulpenox** [Regaddi/Chart.StackedBar.js#24]
I noticed this when I was working with data being build by JSON calls. I started seeing graphs being displayed like so: 

![issue_example](https://cloud.githubusercontent.com/assets/11160353/6421495/3fee6898-be95-11e4-81f1-5608bdf44ae6.png)

After a bit of testing and looking into the original Chart.js I noticed that the values being returned for the y-positioning of bars, as well as the dataTotal() values, were simply each data value appended to each other. The easiest fix I found for this was changing:

// Line 68
offset += datasets[i].bars[barIndex].value;
->
offset = +offset + +datasets[i].bars[barIndex].value;

// Line 379
values[barIndex] += bar.value;
->
values[barIndex] = +values[barIndex] + +bar.value;

I suppose you could also initially send the data arrays as integers, but this seems the simplest fix. Hopefully this helps for anyone else getting these funky bar graphs.

EDIT: Will send a pull request in a bit when I get it sorted out.

**Comment by Regaddi** [comment]
Pull Request?

**Comment by Vulpenox** [comment]
As a side-note, the easiest way to test this error for yourself is to add ''+ to the randomScalingFactor in the stacked-bar.html sample page available. This way the variable returns strings of integers. Example:

// Line 14
var randomScalingFactor = function(){ return Math.round(Math.random()*100)};
->
var randomScalingFactor = function(){ return '' + Math.round(Math.random()*100)};

**Comment by Vulpenox** [comment]
Would you prefer I commit to development or create a new branch to pull request?

**Comment by Regaddi** [comment]
Create a pr-branch :) Thanks in advance!
