### ISSUE TITLE
StackedBar chart keeps animating

### ISSUE THREAD

**Issue by GREdens** [Regaddi/Chart.StackedBar.js#26]
I would like to be able to pass the animation boolean that is part of the normal settings. And that the stacked barchart is not animated.

**Comment by Regaddi** [comment]
You can do that, by setting animation off globally:

    Chart.defaults.global.animation = false;

[See Chart.js Docs](http://www.chartjs.org/docs/#getting-started-global-chart-configuration)

This is the default way of doing this, the other chart types don't have an "animation" option either.
