### ISSUE TITLE
Updates for Chart.js Core

### ISSUE THREAD

**Issue by tannerlinsley** [Regaddi/Chart.StackedBar.js#32]
With the latest PR's, there is now a new update function style that allow users to edit data straight from the chart config object.  Check out this PR for more details: https://github.com/nnnick/Chart.js/commit/a8063de6b8a744b0ad117d20ef7c9138147212f3

There was also one done with a new animation service that improved multi-chart animations a ton.  You can find that one here: https://github.com/nnnick/Chart.js/commit/5443886ec3193d6a183f2dd167fee7782652a2ff

The core charts have been updated to support this new style.  Let's get the stacked bar in there too!

**Comment by tannerlinsley** [comment]
Looks like there are no changes to be made to take advantage of the new animation service.

**Comment by Regaddi** [comment]
Thanks @tannerlinsley!
