### ISSUE TITLE
Unable to add null value to chart

### ISSUE THREAD

**Issue by twentynine12** [Regaddi/Chart.StackedBar.js#34]
First of all, loving your extension, good work.

I suspect this is a request as opposed to a bug/issue but when I pass a null into a dataset it'd be great if it accepted a null in the dataset which would be treated as a value but not shown on the graph.

Currently if you pass a null in the data the graph doesn't draw correctly - http://jsfiddle.net/twentynine12/roqLo4dr/.  You can pass a 0 but it still shows in the label.

Let me know what you think, or if you can figure out a workaround.

Thanks.

**Comment by wanibani** [comment]
Hey 2912,
The behaviour ist exactly as you described:
null will be rendered as 0 within graph, but not shown in tooltip; all graph types treat null like this.
But i can confirm your problem: ignore null during rendering and allow "gaps" in graphs would be nice ;-)
cheers
