### ISSUE TITLE
How can I show value on the bar graph

### ISSUE THREAD

**Issue by Juckky00** [Regaddi/Chart.StackedBar.js#40]
like this :
![test](https://cloud.githubusercontent.com/assets/12996384/8681759/8f87a210-2a93-11e5-9622-031ec0c706ba.PNG)

 Thank you.

**Comment by Regaddi** [comment]
Hi @Juckky00,

unfortunately this has nothing to do with this repository.
Feel free to open an issue at https://github.com/nnnick/Chart.js/issues
