### ISSUE TITLE
Chart doesn't update on data change

### ISSUE THREAD

**Issue by alevinru** [Regaddi/Chart.StackedBar.js#44]
Because chart.js uses chart.datasets but Chart.StackedBar.js uses this.data.datasets in the update function: https://github.com/jtblin/angular-chart.js/blob/master/angular-chart.js#L293

**Comment by jameshoward** [comment]
The latest Bower / NPM versions (1.0.3) don't contain this fix. Would you be able to release a 1.0.4 please? Thanks
