### ISSUE TITLE
Add to npm registry

### ISSUE THREAD

**Issue by esbenp** [Regaddi/Chart.StackedBar.js#46]
Could this please be added to the npm registry so it is installable using npm? :-)

**Comment by byCedric** [comment]
The best part of this is that there _is_ a package.json file, and therefore you think it's publicly accessible using NPM. Unfortunately, the flag private is set to true which tells NPM that this should not be added to the registry.

So to achieve this, please remove the `private: true` statement within `package.json` and add it to the registry. :) If you want I can make a pull request for removing the private statement.

**Comment by swillard-r7** [comment]
+1 Would really appreciate this

**Comment by zeropaper** [comment]
:+1:  Agree that would be avoid downloading the file manually and having a "vendor" directory.

**Comment by ArnaudD** [comment]
Workaround :

```
npm install --save-dev Regaddi/Chart.StackedBar.js
```

**Comment by Regaddi** [comment]
Published as NPM package.

https://www.npmjs.com/package/chart-stackedbar-js
