### ISSUE TITLE
Update StackedBar to support CharJS 2.0 releases

### ISSUE THREAD

**Issue by ArthurPBressan** [Regaddi/Chart.StackedBar.js#48]
I need to use ChartJS 2.0 multiple Y axes on a few charts, but I still need to use StackedBar for every other chart on my page.

ChartJS 2.0 is still in beta however, so I don't know if StackedBar is just waiting for that to come out so it can then upgrade.

**Comment by Regaddi** [comment]
I will wait for the first final release on 2.0 and then have a check on the upgrades.
