### ISSUE TITLE
Vertical labels

### ISSUE THREAD

**Issue by RWOverdijk** [Regaddi/Chart.StackedBar.js#54]
Hey,

cool thing you made :) I like the way it works but have one small problem, being the vertical count (on the left). 

It currently takes the count and makes those steps and makes this (https://www.dropbox.com/s/uply1p28upv0be2/Screenshot%202016-01-07%2022.20.14.png?dl=0) I want it to go up to 350000 in stead of 327680. Is there an option for that?

**Comment by Regaddi** [comment]
I think you can overwrite this using the `scaleOverride` configuration option.

Check out the [Chart.js docs](http://www.chartjs.org/docs/#getting-started-global-chart-configuration) for this.

**Comment by RWOverdijk** [comment]
Ah, I went ahead and used highcharts. Forgot to close this. Thanks for the answer though :)
